name: Hello World

on:
    push:
        branches: [ '**' ]

jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Print Hello World
              run: echo "Hello, World!"
        
            - name: Print date and time
              run: date
    job-two:
        name: Second Job
        runs-on: ubuntu-latest
        needs: say-hello
        steps:
            - name: Print a message from the second job
              run: echo "This is the second job running after the first job."
    
    