name: Hello World

on:
    push:
        branches: [ '**' ]

jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Print Hello World
              run: echo "Hello, World!"
        
            - name: Print date and time
              run: date
