name: Run Tests

on:
    push:
        branches: [main, develop, experiment/*]
    pull_request:
        branches: [main, develop]
    
jobs:
  # check linting
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
            python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
            enable-cache: true
      
      - name: Install dependencies
        run: |
          uv sync --frozen
          uv pip install ruff
            
      - name: Run Ruff linting and formatting checks
        run: |
          uv run ruff check .
          uv run ruff format --check .
        
  tests:
      name: Run Tests
      runs-on: ubuntu-latest
      needs: quality

      # start a PostgreSQL service
      services:
          postgres:
              image: postgres:15
              env:
                  POSTGRES_USER: testuser
                  POSTGRES_PASSWORD: testpassword
                  POSTGRES_DB: testdb
              options: >-
                  --health-cmd pg_isready
                  --health-interval 10s
                  --health-timeout 5s
                  --health-retries 5
              ports:
                  - 5432:5432

      steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python 3.13
            uses: actions/setup-python@v5
            with:
                python-version: 3.13

          - name: Install uv
            uses: astral-sh/setup-uv@v4
            with:
                enable-cache: true
          
          - name: Install dependencies
            run: uv sync --frozen

          # run tests
          - name: Run tests with coverage
            env:
              DB_USER: testuser
              DB_PASSWORD: testpassword
              DB_NAME: testdb
              DB_HOST: localhost
              DB_PORT: 5432
            run: uv run pytest --cov=app tests/ --cov-report=xml --cov-fail-under=80

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: tests
    # add startsWith(github.ref, 'refs/heads/experiment/') for development branches
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/experiment/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest

      
          
